### ISSUE TITLE
Integrate with buttplug.io

### ISSUE THREAD

**Issue by programotter** [ugraveknight/Healslut-Master#1]
https://buttplug.io/

This would be awesome, since it enables interactivity with a whole set of toys :D

Unfortunately there's no Python library, so integration would need to be either by implementing the data spec in Python, adapting to C# or JavaScript, or by calling out to a simple client adaptor written in one of those languages.

**Comment by programotter** [comment]
Oh wait look, there's a Python client library! https://github.com/buttplugio/buttplug-py

**Comment by programotter** [comment]
But it's deeply incomplete :(

**Comment by ugraveknight** [comment]
Hey thanks for the input, I'm actually in contact with qDot who runs that project. Hopefully we'll have good news for you in the near future!
