### ISSUE TITLE
Can spaces be standardized on for indentation

### ISSUE THREAD

**Issue by this-is-embarrassing** [ugraveknight/Healslut-Master#3]
I just noticed python doesn't like my patch because I used spaces.
Also the banner art in HealslutMaster.py is a mix of spaces and tabs so It won't look right for everyone.

**Comment by ugraveknight** [comment]
I'll do my best to standardize where possible in regards to the banner art. I understand that pep8 advises spaces over tabs, but the environment I work in is exclusively tab based. I do not foresee myself moving to space-centric standardization. 

You're probably right that it would be convenient for the masses, but it would ruin me.
